# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xIdTcl95TDYlWlRtEGYlJTuqWeierQaU
"""

def fibonacci(length):
  x = [1,2] # initialize the 2 first number in list
  
  if length <=20: #limit the length of fibonacci
    for i in range(length-len(x)): 
      x.append(x[-1]+x[-2])
    print("\n=======================\n")
    print("your fibonacci number: \n")
    return x
  else:
    return "\nlength must be less or equal than 20"

print("input length of fibonacci: ")
length_fibonacci = int(input())

print(fibonacci(length_fibonacci))