# -*- coding: utf-8 -*-
"""palindrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rgHdMbVXuaAS0woDkc_4B5l9Kf69ynGC
"""

def palindrome(input):
	text = input.lower()
	original_text = ""
	reversed_text = ""

	for alphabet in text:
		if alphabet.isalpha():
			original_text += alphabet
		elif alphabet.isnumeric():
			original_text += alphabet
		else:
			alphabet = alphabet.replace(alphabet, "")
			original_text += alphabet		 
	
	reversed_text = original_text[::-1]
	return original_text == reversed_text

print(palindrome("kayak")) # will return True
print(palindrome("abc")) # will return False
print(palindrome("3...53")) # will return True
print(palindrome("5212316")) # will return False
print(palindrome("Able was I ere I saw Elba!")) # will return True